name: Bug Report
description: Report a bug in aivid
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run `aivid video.mp4`
        2. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error output
      description: Please copy and paste any relevant error output
      render: shell

  - type: input
    id: version
    attributes:
      label: aivid version
      description: Run `aivid --version` to get the version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "3.12"
    validations:
      required: true

  - type: checkboxes
    id: tools
    attributes:
      label: System tools installed
      options:
        - label: ffprobe
        - label: mediainfo
        - label: exiftool
